# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5a71f61e42b9dff0986a2bf23b65a24eec838233c9a43321512060fc9e3280f65d57ab8b5f68445c2ccac6558510f88e6e18ce5b916124d5e15cb673d0e651

test:
  secret_key_base: 5753b937931fc7274141ca682f075aa6a628e991496c821b78d2ed75801c2c3e3875c18899f57f809abcf101a33301e8a389a808a8049afa38875fcad8c2b503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
